version: '3.8'
services:
#  mongo:
#    image: mongo:6.0.1
#    restart: unless-stopped
#    ports:
#      - '27017:27017'
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.37
    restart: unless-stopped
    ports:
      - '16686:16686' # Jaeger UI
      - '14250:14250' # Jaeger Exporter
