server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
  show-actuator: true
spring:
  application:
    name: bootelemetry
  main:
    banner-mode: off
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  tracing:
    sampling:
      probability: 1.0 # Be careful with this in a production environment
otel:
  span-exporter-endpoint: ${SPAN_EXPORTER_ENDPOINT:http://localhost:4317}