global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus-monitoring-job'
    static_configs:
      - targets: [localhost:9090]
  - job_name: 'bootelemetry-monitoring-job'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [host.docker.internal:8080]
