server:
  port: ${PORT:8080}
  shutdown: graceful
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: bootelemetry-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/bootelemetry}
      auto-index-creation: false
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        jaeger:
          endpoint: http://localhost:14250
    propagation:
      type: jaeger
